In [1]:
import pandas as pd
import numpy as np

In [2]:
df=pd.read_csv('/Users/sagar/Desktop/imdbb.csv')

In [4]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5043 entries, 0 to 5042
Data columns (total 28 columns):
color                        5024 non-null object
director_name                4939 non-null object
num_critic_for_reviews       4993 non-null float64
duration                     5028 non-null float64
director_facebook_likes      4939 non-null float64
actor_3_facebook_likes       5020 non-null float64
actor_2_name                 5030 non-null object
actor_1_facebook_likes       5036 non-null float64
gross                        4159 non-null float64
genres                       5043 non-null object
actor_1_name                 5036 non-null object
movie_title                  5043 non-null object
num_voted_users              5043 non-null int64
cast_total_facebook_likes    5043 non-null int64
actor_3_name                 5020 non-null object
facenumber_in_poster         5030 non-null float64
plot_keywords                4890 non-null object
movie_imdb_link              5043 non-null object
num_user_for_reviews         5022 non-null float64
language                     5031 non-null object
country                      5038 non-null object
content_rating               4740 non-null object
budget                       4551 non-null float64
title_year                   4935 non-null float64
actor_2_facebook_likes       5030 non-null float64
imdb_score                   5043 non-null float64
aspect_ratio                 4714 non-null float64
movie_facebook_likes         5043 non-null int64
dtypes: float64(13), int64(3), object(12)
memory usage: 1.1+ MB

In [7]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
count,4993.000000,5028.000000,4939.000000,5020.000000,5036.000000,4.159000e+03,5.043000e+03,5043.000000,5030.000000,5022.000000,4.551000e+03,4935.000000,5030.000000,5043.000000,4714.000000,5043.000000
mean,140.194272,107.201074,686.509212,645.009761,6560.047061,4.846841e+07,8.366816e+04,9699.063851,1.371173,272.770808,3.975262e+07,2002.470517,1651.754473,6.442138,2.220403,7525.964505
std,121.601675,25.197441,2813.328607,1665.041728,15020.759120,6.845299e+07,1.384853e+05,18163.799124,2.013576,377.982886,2.061149e+08,12.474599,4042.438863,1.125116,1.385113,19320.445110
min,1.000000,7.000000,0.000000,0.000000,0.000000,1.620000e+02,5.000000e+00,0.000000,0.000000,1.000000,2.180000e+02,1916.000000,0.000000,1.600000,1.180000,0.000000
25%,50.000000,93.000000,7.000000,133.000000,614.000000,5.340988e+06,8.593500e+03,1411.000000,0.000000,65.000000,6.000000e+06,1999.000000,281.000000,5.800000,1.850000,0.000000
50%,110.000000,103.000000,49.000000,371.500000,988.000000,2.551750e+07,3.435900e+04,3090.000000,1.000000,156.000000,2.000000e+07,2005.000000,595.000000,6.600000,2.350000,166.000000
75%,195.000000,118.000000,194.500000,636.000000,11000.000000,6.230944e+07,9.630900e+04,13756.500000,2.000000,326.000000,4.500000e+07,2011.000000,918.000000,7.200000,2.350000,3000.000000
max,813.000000,511.000000,23000.000000,23000.000000,640000.000000,7.605058e+08,1.689764e+06,656730.000000,43.000000,5060.000000,1.221550e+10,2016.000000,137000.000000,9.500000,16.000000,349000.000000

In [11]:
df1 = df.drop(['duration', 'aspect_ratio'], axis=1)

In [16]:
list(df1.columns.values)

['color',
 'director_name',
 'num_critic_for_reviews',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'movie_facebook_likes']

In [31]:
df1.sort_values(by='movie_facebook_likes', ascending=False)

,color,director_name,num_critic_for_reviews,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,...,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,movie_facebook_likes
96,Color,Christopher Nolan,712.0,22000.0,6000.0,Anne Hathaway,11000.0,187991439.0,Adventure|Drama|Sci-Fi,Matthew McConaughey,...,http://www.imdb.com/title/tt0816692/?ref_=fn_t...,2725.0,English,USA,PG-13,165000000.0,2014.0,11000.0,8.6,349000
296,Color,Quentin Tarantino,765.0,16000.0,265.0,Christoph Waltz,29000.0,162804648.0,Drama|Western,Leonardo DiCaprio,...,http://www.imdb.com/title/tt1853728/?ref_=fn_t...,1193.0,English,USA,R,100000000.0,2012.0,11000.0,8.5,199000
10,Color,Zack Snyder,673.0,0.0,2000.0,Lauren Cohan,15000.0,330249062.0,Action|Adventure|Sci-Fi,Henry Cavill,...,http://www.imdb.com/title/tt2975590/?ref_=fn_t...,3018.0,English,USA,PG-13,250000000.0,2016.0,4000.0,6.9,197000
128,Color,George Miller,739.0,750.0,943.0,Charlize Theron,27000.0,153629485.0,Action|Adventure|Sci-Fi|Thriller,Tom Hardy,...,http://www.imdb.com/title/tt1392190/?ref_=fn_t...,1588.0,English,Australia,R,150000000.0,2015.0,9000.0,8.1,191000
179,Color,Alejandro G. IÃ±Ã¡rritu,556.0,0.0,733.0,Tom Hardy,29000.0,183635922.0,Adventure|Drama|Thriller|Western,Leonardo DiCaprio,...,http://www.imdb.com/title/tt1663202/?ref_=fn_t...,1188.0,English,USA,R,135000000.0,2015.0,27000.0,8.1,190000
97,Color,Christopher Nolan,642.0,22000.0,23000.0,Tom Hardy,29000.0,292568851.0,Action|Adventure|Sci-Fi|Thriller,Leonardo DiCaprio,...,http://www.imdb.com/title/tt1375666/?ref_=fn_t...,2803.0,English,USA,PG-13,160000000.0,2010.0,27000.0,8.8,175000
99,Color,Peter Jackson,645.0,0.0,773.0,Adam Brown,5000.0,303001229.0,Adventure|Fantasy,Aidan Turner,...,http://www.imdb.com/title/tt0903624/?ref_=fn_t...,1367.0,English,USA,PG-13,180000000.0,2012.0,972.0,7.9,166000
2614,Color,Morten Tyldum,454.0,77.0,305.0,Rory Kinnear,19000.0,91121452.0,Biography|Drama|Thriller|War,Benedict Cumberbatch,...,http://www.imdb.com/title/tt2084970/?ref_=fn_t...,608.0,English,UK,PG-13,14000000.0,2014.0,393.0,8.1,165000
3,Color,Christopher Nolan,813.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,164000
278,Color,Ridley Scott,568.0,0.0,372.0,Donald Glover,13000.0,228430993.0,Adventure|Drama|Sci-Fi,Matt Damon,...,http://www.imdb.com/title/tt3659388/?ref_=fn_t...,1023.0,English,USA,PG-13,108000000.0,2015.0,801.0,8.1,153000
29,Color,Colin Trevorrow,644.0,365.0,1000.0,Judy Greer,3000.0,652177271.0,Action|Adventure|Sci-Fi|Thriller,Bryce Dallas Howard,...,http://www.imdb.com/title/tt0369610/?ref_=fn_t...,1290.0,English,USA,PG-13,150000000.0,2015.0,2000.0,7.0,150000
1578,Color,Wes Anderson,536.0,0.0,670.0,Tom Wilkinson,13000.0,59073773.0,Adventure|Comedy|Crime|Drama,Bill Murray,...,http://www.imdb.com/title/tt2278388/?ref_=fn_t...,644.0,English,USA,R,25000000.0,2014.0,1000.0,8.1,149000
2058,Color,Spike Jonze,574.0,0.0,105.0,Brian Johnson,19000.0,25556065.0,Drama|Romance|Sci-Fi,Scarlett Johansson,...,http://www.imdb.com/title/tt1798709/?ref_=fn_t...,748.0,English,USA,R,23000000.0,2013.0,128.0,8.0,148000
246,Color,Alfonso CuarÃ³n,738.0,0.0,13.0,Basher Savage,39.0,274084951.0,Adventure|Drama|Sci-Fi|Thriller,Phaldut Sharma,...,http://www.imdb.com/title/tt1454468/?ref_=fn_t...,1885.0,English,UK,PG-13,100000000.0,2013.0,23.0,7.8,147000
715,Color,David Fincher,568.0,21000.0,625.0,Sela Ward,835.0,167735396.0,Crime|Drama|Mystery|Thriller,Patrick Fugit,...,http://www.imdb.com/title/tt2267998/?ref_=fn_t...,1127.0,English,USA,R,61000000.0,2014.0,812.0,8.1,146000
658,Color,Tom Hooper,488.0,0.0,11000.0,Eddie Redmayne,20000.0,148775460.0,Drama|Musical|Romance,Hugh Jackman,...,http://www.imdb.com/title/tt1707386/?ref_=fn_t...,845.0,English,USA,PG-13,61000000.0,2012.0,13000.0,7.6,144000
439,Color,Gary Ross,673.0,378.0,575.0,Josh Hutcherson,34000.0,407999255.0,Adventure|Drama|Sci-Fi|Thriller,Jennifer Lawrence,...,http://www.imdb.com/title/tt1392170/?ref_=fn_t...,1959.0,English,USA,PG-13,78000000.0,2012.0,14000.0,7.3,140000
308,Color,Martin Scorsese,606.0,17000.0,4000.0,Matthew McConaughey,29000.0,116866727.0,Biography|Comedy|Crime|Drama,Leonardo DiCaprio,...,http://www.imdb.com/title/tt0993846/?ref_=fn_t...,1138.0,English,USA,R,100000000.0,2013.0,11000.0,8.2,138000
2163,Color,James Wan,511.0,0.0,697.0,Lili Taylor,6000.0,137387272.0,Horror|Mystery|Thriller,Mackenzie Foy,...,http://www.imdb.com/title/tt1457767/?ref_=fn_t...,807.0,English,USA,R,20000000.0,2013.0,960.0,7.5,131000
2884,Color,Stephen Chbosky,364.0,139.0,850.0,Ezra Miller,8000.0,17738570.0,Drama|Romance,Logan Lerman,...,http://www.imdb.com/title/tt1659337/?ref_=fn_t...,457.0,English,USA,PG-13,13000000.0,2012.0,3000.0,8.0,131000
46,Color,Marc Forster,654.0,395.0,1000.0,Brad Pitt,17000.0,202351611.0,Action|Adventure|Horror|Sci-Fi|Thriller,Peter Capaldi,...,http://www.imdb.com/title/tt0816711/?ref_=fn_t...,995.0,English,USA,PG-13,190000000.0,2013.0,11000.0,7.0,129000
4028,Color,Damien Chazelle,535.0,141.0,535.0,Melissa Benoist,24000.0,13092000.0,Drama|Music,J.K. Simmons,...,http://www.imdb.com/title/tt2582802/?ref_=fn_t...,731.0,English,USA,R,3300000.0,2014.0,970.0,8.5,129000
311,Color,Tom Tykwer,511.0,670.0,1000.0,Jim Sturgess,15000.0,27098580.0,Drama|Sci-Fi,Tom Hanks,...,http://www.imdb.com/title/tt1371111/?ref_=fn_t...,828.0,English,Germany,R,102000000.0,2012.0,5000.0,7.5,124000
17,Color,Joss Whedon,703.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,...,http://www.imdb.com/title/tt0848228/?ref_=fn_t...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,123000
268,Color,Gavin Hood,326.0,151.0,430.0,Moises Arias,11000.0,61656849.0,Action|Sci-Fi,Harrison Ford,...,http://www.imdb.com/title/tt1731141/?ref_=fn_t...,554.0,English,USA,PG-13,110000000.0,2013.0,635.0,6.7,123000
794,Color,Joss Whedon,703.0,0.0,19000.0,Robert Downey Jr.,26000.0,623279547.0,Action|Adventure|Sci-Fi,Chris Hemsworth,...,http://www.imdb.com/title/tt0848228/?ref_=fn_t...,1722.0,English,USA,PG-13,220000000.0,2012.0,21000.0,8.1,123000
223,Color,Ang Lee,552.0,0.0,341.0,Rafe Spall,774.0,124976634.0,Adventure|Drama|Fantasy,Suraj Sharma,...,http://www.imdb.com/title/tt0454876/?ref_=fn_t...,755.0,English,USA,PG,120000000.0,2012.0,358.0,8.0,122000
15,Color,Zack Snyder,733.0,0.0,748.0,Christopher Meloni,15000.0,291021565.0,Action|Adventure|Fantasy|Sci-Fi,Henry Cavill,...,http://www.imdb.com/title/tt0770828/?ref_=fn_t...,2536.0,English,USA,PG-13,225000000.0,2013.0,3000.0,7.2,118000
8,Color,Joss Whedon,635.0,0.0,19000.0,Robert Downey Jr.,26000.0,458991599.0,Action|Adventure|Sci-Fi,Chris Hemsworth,...,http://www.imdb.com/title/tt2395427/?ref_=fn_t...,1117.0,English,USA,PG-13,250000000.0,2015.0,21000.0,7.5,118000
78,Color,Pete Docter,536.0,0.0,384.0,Mindy Kaling,1000.0,356454367.0,Adventure|Animation|Comedy|Drama|Family|Fantasy,Amy Poehler,...,http://www.imdb.com/title/tt2096673/?ref_=fn_t...,773.0,English,USA,PG,175000000.0,2015.0,767.0,8.3,118000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3165,Color,Joe Nussbaum,52.0,18.0,2000.0,Alexa PenaVega,7000.0,8070311.0,Comedy|Romance,Steve Carell,...,http://www.imdb.com/title/tt0368975/?ref_=fn_t...,75.0,English,USA,PG,10000000.0,2004.0,2000.0,5.3,0
3166,Color,Brian De Palma,98.0,0.0,298.0,Dennis Franz,537.0,NaN,Mystery|Thriller,Melanie Griffith,...,http://www.imdb.com/title/tt0086984/?ref_=fn_t...,178.0,English,USA,R,10000000.0,1984.0,376.0,6.8,0
3167,Color,Jorma Taccone,163.0,434.0,472.0,Will Forte,1000.0,8460995.0,Action|Comedy|Romance,Jasper Cole,...,http://www.imdb.com/title/tt1470023/?ref_=fn_t...,125.0,English,USA,R,10000000.0,2010.0,622.0,5.5,0
3168,Color,Stephen Frears,137.0,350.0,250.0,Benedict Wong,460.0,8111360.0,Crime|Drama|Thriller,Sophie Okonedo,...,http://www.imdb.com/title/tt0301199/?ref_=fn_t...,203.0,English,UK,R,10000000.0,2002.0,372.0,7.4,0
1242,Black and White,Iain Softley,193.0,34.0,280.0,Deneen Tyler,545.0,47806295.0,Horror|Mystery|Thriller,Gena Rowlands,...,http://www.imdb.com/title/tt0397101/?ref_=fn_t...,371.0,English,USA,PG-13,43000000.0,2005.0,351.0,6.5,0
1241,Color,Alejandro Agresti,175.0,18.0,211.0,Dylan Walsh,18000.0,52320979.0,Drama|Fantasy|Romance,Keanu Reeves,...,http://www.imdb.com/title/tt0410297/?ref_=fn_t...,548.0,English,USA,PG,40000000.0,2006.0,426.0,6.8,0
1240,Color,David Koepp,195.0,192.0,501.0,Charles S. Dutton,40000.0,47781388.0,Mystery|Thriller,Johnny Depp,...,http://www.imdb.com/title/tt0363988/?ref_=fn_t...,531.0,English,USA,PG-13,40000000.0,2004.0,534.0,6.6,0
3173,Color,Miguel Arteta,212.0,44.0,727.0,Stephen Root,1000.0,6857503.0,Comedy,Kurtwood Smith,...,http://www.imdb.com/title/tt1477837/?ref_=fn_t...,85.0,English,USA,R,NaN,2011.0,939.0,6.3,0
3174,Color,NaN,68.0,NaN,476.0,T.J. Thyne,1000.0,NaN,Comedy|Crime|Drama|Mystery|Romance,Michaela Conlin,...,http://www.imdb.com/title/tt0460627/?ref_=fn_t...,173.0,English,USA,TV-14,NaN,NaN,722.0,7.9,0
1252,Color,Joan Chen,101.0,643.0,586.0,Sam Trammell,24000.0,37752931.0,Drama|Romance,J.K. Simmons,...,http://www.imdb.com/title/tt0174480/?ref_=fn_t...,180.0,English,USA,PG-13,40000000.0,2000.0,1000.0,5.5,0
1253,Color,Marc Lawrence,175.0,30.0,664.0,Scott Porter,799.0,50562555.0,Comedy|Music|Romance,Brad Garrett,...,http://www.imdb.com/title/tt0758766/?ref_=fn_t...,291.0,English,USA,PG-13,NaN,2007.0,690.0,6.5,0
3153,Color,Neal Brennan,83.0,23.0,503.0,Noureen DeWulf,839.0,15102127.0,Comedy,Rob Riggle,...,http://www.imdb.com/title/tt1092633/?ref_=fn_t...,59.0,English,USA,R,NaN,2009.0,700.0,5.8,0
1270,Color,Roger Michell,212.0,50.0,58.0,Patti D'Arbanville,293.0,30993544.0,Comedy|Drama|Romance,Noah Bean,...,http://www.imdb.com/title/tt1126618/?ref_=fn_t...,156.0,English,USA,PG-13,40000000.0,2010.0,117.0,6.5,0
3127,Color,Harry Elfont,76.0,4.0,678.0,Lauren Ambrose,982.0,25339117.0,Comedy|Romance,Ethan Embry,...,http://www.imdb.com/title/tt0127723/?ref_=fn_t...,247.0,English,USA,PG-13,10000000.0,1998.0,945.0,6.5,0
1276,Color,John Frankenheimer,70.0,287.0,44.0,Temuera Morrison,10000.0,27663982.0,Horror|Sci-Fi|Thriller,Marlon Brando,...,http://www.imdb.com/title/tt0116654/?ref_=fn_t...,164.0,English,USA,PG-13,40000000.0,1996.0,368.0,4.4,0
3130,Color,David Cronenberg,112.0,0.0,275.0,Herbert Lom,1000.0,NaN,Horror|Sci-Fi|Thriller,Tom Skerritt,...,http://www.imdb.com/title/tt0085407/?ref_=fn_t...,182.0,English,USA,R,10000000.0,1983.0,278.0,7.2,0
3132,Color,Salim Akil,82.0,70.0,706.0,Curtis Armstrong,1000.0,24397469.0,Drama|Music,Omari Hardwick,...,http://www.imdb.com/title/tt1876451/?ref_=fn_t...,48.0,English,USA,PG-13,17000000.0,2012.0,876.0,5.7,0
3133,Color,Jamie Blanks,120.0,9.0,448.0,Jessica Capshaw,690.0,20384136.0,Horror|Mystery|Thriller,Marley Shelton,...,http://www.imdb.com/title/tt0242998/?ref_=fn_t...,371.0,English,USA,R,10000000.0,2001.0,533.0,4.7,0
1271,Color,Jim Sheridan,98.0,260.0,441.0,Bill Duke,1000.0,30981850.0,Biography|Crime|Drama|Music,50 Cent,...,http://www.imdb.com/title/tt0430308/?ref_=fn_t...,284.0,English,USA,R,40000000.0,2005.0,1000.0,5.0,0
3137,Color,Joseph Zito,54.0,17.0,53.0,Richard Lynch,371.0,NaN,Action|Thriller,Billy Drago,...,http://www.imdb.com/title/tt0089348/?ref_=fn_t...,90.0,English,USA,R,10000000.0,1985.0,324.0,5.3,0
1268,Color,Russell Mulcahy,70.0,85.0,510.0,Peter Boyle,924.0,32055248.0,Action|Adventure|Crime|Fantasy|Mystery|Thriller,Jonathan Winters,...,http://www.imdb.com/title/tt0111143/?ref_=fn_t...,146.0,English,USA,PG-13,25000000.0,1994.0,595.0,6.0,0
3152,Color,Morgan Spurlock,83.0,293.0,547.0,Zayn Malik,773.0,28873374.0,Documentary|Music,Harry Styles,...,http://www.imdb.com/title/tt2515086/?ref_=fn_t...,68.0,English,USA,PG,10000000.0,2013.0,734.0,4.1,0
1264,Color,Bobby Farrelly,124.0,101.0,223.0,KaDee Strickland,787.0,42071069.0,Comedy|Drama|Romance|Sport,Jimmy Fallon,...,http://www.imdb.com/title/tt0332047/?ref_=fn_t...,208.0,English,USA,PG-13,30000000.0,2005.0,299.0,6.2,0
1259,Color,Jake Kasdan,201.0,52.0,214.0,Randall Park,683.0,38543473.0,Comedy,James Wilcox,...,http://www.imdb.com/title/tt1956620/?ref_=fn_t...,158.0,English,USA,R,40000000.0,2014.0,392.0,5.1,0
3145,Color,Steve Oedekerk,63.0,176.0,39.0,Simon Rhee,176.0,16033556.0,Action|Comedy,Steve Oedekerk,...,http://www.imdb.com/title/tt0240468/?ref_=fn_t...,518.0,English,USA,PG-13,10000000.0,2002.0,67.0,6.2,0
1258,Color,Oliver Stone,82.0,0.0,552.0,Kevin Dillon,720.0,35183792.0,Biography|Drama|Music|Musical,Michael Wincott,...,http://www.imdb.com/title/tt0101761/?ref_=fn_t...,209.0,English,USA,R,38000000.0,1991.0,576.0,7.2,0
3147,Color,Rob Schmidt,191.0,36.0,648.0,Lindy Booth,2000.0,15417771.0,Horror|Thriller,Kevin Zegers,...,http://www.imdb.com/title/tt0295700/?ref_=fn_t...,540.0,English,USA,R,12600000.0,2003.0,683.0,6.1,0
1257,Color,Joel Schumacher,138.0,541.0,173.0,Chris Bauer,12000.0,36283504.0,Mystery|Thriller,Nicolas Cage,...,http://www.imdb.com/title/tt0134273/?ref_=fn_t...,587.0,English,Germany,R,40000000.0,1999.0,638.0,6.5,0
1255,Color,Anne Fletcher,147.0,98.0,78.0,Tom Virtue,405.0,37101011.0,Comedy|Drama,Miriam Margolyes,...,http://www.imdb.com/title/tt1694020/?ref_=fn_t...,103.0,English,USA,PG-13,40000000.0,2012.0,358.0,5.8,0
1006,Color,John Carpenter,104.0,0.0,764.0,Valeria Golino,12000.0,25407250.0,Action|Adventure|Sci-Fi|Thriller,Steve Buscemi,...,http://www.imdb.com/title/tt0116225/?ref_=fn_t...,227.0,English,USA,R,50000000.0,1996.0,898.0,5.7,0

In [33]:
list(df1.columns.values)

['color',
 'director_name',
 'num_critic_for_reviews',
 'director_facebook_likes',
 'actor_3_facebook_likes',
 'actor_2_name',
 'actor_1_facebook_likes',
 'gross',
 'genres',
 'actor_1_name',
 'movie_title',
 'num_voted_users',
 'cast_total_facebook_likes',
 'actor_3_name',
 'facenumber_in_poster',
 'plot_keywords',
 'movie_imdb_link',
 'num_user_for_reviews',
 'language',
 'country',
 'content_rating',
 'budget',
 'title_year',
 'actor_2_facebook_likes',
 'imdb_score',
 'movie_facebook_likes']

In [39]:
df1['content_rating'].value_counts()

R            2118
PG-13        1461
PG            701
Not Rated     116
G             112
Unrated        62
Approved       55
TV-14          30
TV-MA          20
TV-PG          13
X              13
TV-G           10
Passed          9
NC-17           7
GP              6
M               5
TV-Y7           1
TV-Y            1
Name: content_rating, dtype: int64

In [45]:
df1['actor_1_name'].value_counts()

Robert De Niro            49
Johnny Depp               41
Nicolas Cage              33
J.K. Simmons              31
Denzel Washington         30
Matt Damon                30
Bruce Willis              30
Liam Neeson               29
Steve Buscemi             27
Robin Williams            27
Harrison Ford             27
Jason Statham             26
Bill Murray               26
Robert Downey Jr.         26
Morgan Freeman            25
Tom Cruise                25
Tom Hanks                 24
Keanu Reeves              24
Christian Bale            23
Kevin Spacey              22
Scarlett Johansson        22
Gerard Butler             22
Hugh Jackman              21
Leonardo DiCaprio         21
Anthony Hopkins           21
Sylvester Stallone        21
Philip Seymour Hoffman    20
Will Ferrell              20
Matthew McConaughey       20
Dwayne Johnson            19
                          ..
Sunny Mabrey               1
Mark Valley                1
Jay Mohr                   1
Rene Russo                 1
Karl Malden                1
Charles S. Dutton          1
Chase Ellison              1
Clu Gulager                1
Anupam Kher                1
Mahadeo Shivraj            1
Jeremy W. Auman            1
Jason Momoa                1
Joel Moody                 1
Wei Tang                   1
Paul McCartney             1
Sook-Yin Lee               1
Kasia Smutniak             1
Stana Roumillac            1
Piero MaggiÃ²               1
Gaby Hoffmann              1
Ahna O'Reilly              1
Amir Talai                 1
Mike Howard                1
J.D. Williams              1
Kevin Howarth              1
Ohad Knoller               1
Ashley Williams            1
Gary Weeks                 1
Kirk Cameron               1
Chris Marquette            1
Name: actor_1_name, dtype: int64

In [55]:
df1[(df1.actor_1_name == 'Robert De Niro') & (df1.director_name=='Martin Scorsese')].shape[0]

7

In [48]:
df1['director_name'].value_counts()

Steven Spielberg         26
Woody Allen              22
Clint Eastwood           20
Martin Scorsese          20
Ridley Scott             17
Spike Lee                16
Steven Soderbergh        16
Tim Burton               16
Renny Harlin             15
Oliver Stone             14
John Carpenter           13
Joel Schumacher          13
Sam Raimi                13
Robert Zemeckis          13
Ron Howard               13
Michael Bay              13
Barry Levinson           13
Robert Rodriguez         13
Kevin Smith              12
Shawn Levy               12
Tony Scott               12
Peter Jackson            12
Wes Craven               12
Brian De Palma           12
Richard Donner           12
Rob Reiner               11
Francis Ford Coppola     11
Stephen Frears           11
Richard Linklater        11
Rob Cohen                11
                         ..
Bryan Barber              1
Timothy BjÃ¶rklund         1
Tim Boxell                1
Blair Erickson            1
Robert Hall               1
Bob Spiers                1
Moustapha Akkad           1
Michael Clancy            1
AgustÃ­n DÃ­az Yanes        1
Cecil B. DeMille          1
Asger Leth                1
Joseph Ruben              1
Valeri Milev              1
RZA                       1
Jonathan Kesselman        1
Jean-Jacques Mantello     1
Ralph Nelson              1
Nathan Smith Jones        1
Jackie Earle Haley        1
Courtney Hunt             1
Wally Pfister             1
Morgan Neville            1
Charles S. Dutton         1
Antonio Simoncini         1
Andrew Berends            1
Mickey Liddell            1
Chuck Bowman              1
Malcolm Goodwin           1
Daniel Sackheim           1
Joshua Marston            1
Name: director_name, dtype: int64

In [101]:
df_rdn = df1[df1.actor_1_name == 'Robert De Niro']

In [102]:
df_rdn['genres'].value_counts()

Comedy|Romance                               4
Crime|Drama|Thriller                         4
Crime|Drama                                  3
Comedy|Drama                                 3
Comedy|Crime                                 3
Action|Crime|Thriller                        3
Biography|Crime|Drama                        2
Drama|Horror|Mystery|Thriller                2
Crime|Thriller                               2
Comedy                                       2
Crime|Drama|Romance|Thriller                 1
Action|Crime|Drama|Mystery|Thriller          1
Action|Comedy|Crime|Thriller                 1
Drama|Music|Musical|Romance                  1
Biography|Drama|Sport                        1
Drama|Sci-Fi                                 1
Action|Adventure|Crime|Thriller              1
Drama|War                                    1
Action|Biography|Drama|Sport                 1
Drama|Romance                                1
Action|Drama|Sport|Thriller                  1
Adventure|Drama                              1
Drama|Thriller                               1
Comedy|Sport                                 1
Biography|Drama                              1
Comedy|Crime|Drama                           1
Drama|Horror|Sci-Fi|Thriller                 1
Adventure|Animation|Comedy|Family|Fantasy    1
Crime|Drama|Mystery|Thriller                 1
Action|Crime|Drama|Thriller                  1
Adventure|Animation|Comedy|Family            1
Name: genres, dtype: int64

In [103]:
df_rdn_gn  = df_rdn['genres'].str.split('|',expand=True)

In [104]:
df_rdn_gn

              0          1         2         3         4
293      Comedy    Romance      None      None      None
518   Adventure  Animation    Comedy    Family   Fantasy
541   Adventure  Animation    Comedy    Family      None
632       Crime      Drama  Thriller      None      None
710      Comedy    Romance      None      None      None
783      Comedy      Crime      None      None      None
784      Action      Crime     Drama   Mystery  Thriller
838      Comedy       None      None      None      None
868      Action  Adventure     Crime  Thriller      None
879      Action      Drama     Sport  Thriller      None
920   Biography      Crime     Drama      None      None
1140      Crime      Drama  Thriller      None      None
1168     Action      Crime     Drama  Thriller      None
1209     Comedy      Drama      None      None      None
1281      Crime      Drama   Romance  Thriller      None
1285      Crime      Drama   Mystery  Thriller      None
1337     Comedy      Sport      None      None      None
1411      Crime   Thriller      None      None      None
1463     Action      Crime  Thriller      None      None
1548  Biography      Drama      None      None      None
1605     Comedy      Crime      None      None      None
1655     Action     Comedy     Crime  Thriller      None
1704      Drama     Horror    Sci-Fi  Thriller      None
1714      Crime      Drama      None      None      None
1764     Comedy    Romance      None      None      None
1827     Comedy      Crime     Drama      None      None
1829     Comedy      Drama      None      None      None
1854     Comedy    Romance      None      None      None
1884      Crime      Drama  Thriller      None      None
1901      Drama     Horror   Mystery  Thriller      None
1903  Biography      Crime     Drama      None      None
2045      Drama    Romance      None      None      None
2124      Drama   Thriller      None      None      None
2290     Comedy      Crime      None      None      None
2294  Adventure      Drama      None      None      None
2351     Action  Biography     Drama     Sport      None
2425  Biography      Drama     Sport      None      None
2474      Drama     Horror   Mystery  Thriller      None
2629      Drama        War      None      None      None
2630     Comedy      Drama      None      None      None
2636      Crime      Drama  Thriller      None      None
2700      Drama     Sci-Fi      None      None      None
2794      Drama      Music   Musical   Romance      None
2837      Crime      Drama      None      None      None
2911     Action      Crime  Thriller      None      None
2930      Crime   Thriller      None      None      None
3025     Comedy       None      None      None      None
3317     Action      Crime  Thriller      None      None
4535      Crime      Drama      None      None      None

In [70]:
df_rdn_gn= df_rdn_gn['0'] + df_rdn_gn['1']

KeyError: '0'

In [105]:
len(df_rdn_gn)

49

In [106]:
df_rdn_gn_z = df_rdn_gn.loc[:,:'0']
df_rdn_gn_o = df_rdn_gn.loc[:,:'1']
df_rdn_gn_tw = df_rdn_gn.loc[:,:'2']
df_rdn_gn_th = df_rdn_gn.loc[:,:'3']

In [107]:
df_rdn_gn_z

              0
293      Comedy
518   Adventure
541   Adventure
632       Crime
710      Comedy
783      Comedy
784      Action
838      Comedy
868      Action
879      Action
920   Biography
1140      Crime
1168     Action
1209     Comedy
1281      Crime
1285      Crime
1337     Comedy
1411      Crime
1463     Action
1548  Biography
1605     Comedy
1655     Action
1704      Drama
1714      Crime
1764     Comedy
1827     Comedy
1829     Comedy
1854     Comedy
1884      Crime
1901      Drama
1903  Biography
2045      Drama
2124      Drama
2290     Comedy
2294  Adventure
2351     Action
2425  Biography
2474      Drama
2629      Drama
2630     Comedy
2636      Crime
2700      Drama
2794      Drama
2837      Crime
2911     Action
2930      Crime
3025     Comedy
3317     Action
4535      Crime

In [108]:
df_rdn_gn = pd.concat([df_rdn_gn_o, df_rdn_gn_tw,df_rdn_gn_th, df_rdn_gn_z], ignore_index=True)

In [120]:
list(df_rdn_gn.columns.values)
#df1 = df.drop(['duration', 'aspect_ratio'], axis=1)

[0, 1, 2, 3]

In [128]:
#df_rdn_gn.drop(columns = ['1'])
#df.drop(columns=['B', 'C'])
df_rdn_gn_now = df_rdn_gn.loc[:,:'0']

In [131]:
df_rdn_gn_now.dropna()

             0
0       Comedy
1    Adventure
2    Adventure
3        Crime
4       Comedy
5       Comedy
6       Action
7       Comedy
8       Action
9       Action
10   Biography
11       Crime
12      Action
13      Comedy
14       Crime
15       Crime
16      Comedy
17       Crime
18      Action
19   Biography
20      Comedy
21      Action
22       Drama
23       Crime
24      Comedy
25      Comedy
26      Comedy
27      Comedy
28       Crime
29       Drama
..         ...
166  Biography
167     Comedy
168     Action
169      Drama
170      Crime
171     Comedy
172     Comedy
173     Comedy
174     Comedy
175      Crime
176      Drama
177  Biography
178      Drama
179      Drama
180     Comedy
181  Adventure
182     Action
183  Biography
184      Drama
185      Drama
186     Comedy
187      Crime
188      Drama
189      Drama
190      Crime
191     Action
192      Crime
193     Comedy
194     Action
195      Crime

[196 rows x 1 columns]

In [143]:
df_rdn_gn_now.describe()

             0
count      196
unique       6
top     Comedy
freq        56

In [144]:
import matplotlib.pyplot as plt

In [149]:
df_rdn_gn_now.groupby

<bound method NDFrame.groupby of              0
0       Comedy
1    Adventure
2    Adventure
3        Crime
4       Comedy
5       Comedy
6       Action
7       Comedy
8       Action
9       Action
10   Biography
11       Crime
12      Action
13      Comedy
14       Crime
15       Crime
16      Comedy
17       Crime
18      Action
19   Biography
20      Comedy
21      Action
22       Drama
23       Crime
24      Comedy
25      Comedy
26      Comedy
27      Comedy
28       Crime
29       Drama
..         ...
166  Biography
167     Comedy
168     Action
169      Drama
170      Crime
171     Comedy
172     Comedy
173     Comedy
174     Comedy
175      Crime
176      Drama
177  Biography
178      Drama
179      Drama
180     Comedy
181  Adventure
182     Action
183  Biography
184      Drama
185      Drama
186     Comedy
187      Crime
188      Drama
189      Drama
190      Crime
191     Action
192      Crime
193     Comedy
194     Action
195      Crime

[196 rows x 1 columns]>

In [3]:
import os
cwd = os.getcwd()
print(cwd)

/Users/sagar